INSERT INTO BESUCH (DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL)
 VALUES ('#{device_id}', '#{mac_prefix}', '#{location_name}', '#{start_time}', '#{end_time}', '#{count}', '#{min_signal}', '#{max_signal}')

SELECT COUNT(*) 
FROM BESUCH 
WHERE 1 = 1
AND DEVICE_ID = '#{device_id}'
ORDER BY END_TIME ASC

UPDATE BESUCH
SET END_TIME = '#{end_time}'
WHERE DEVICE_ID = '#{device_id}'


SELECT * 
FROM BESUCH
WHERE NOT EXISTS (
	SELECT 1
	FROM BLACKLIST
	WHERE BLACKLIST.BLACKLIST_DEVICE = BESUCH.DEVICE_ID
)

SELECT *
FROM BESUCH AS BE
LEFT JOIN BLACKLIST AS BL ON BE.DEVICE_ID = BL.BLACKLIST_DEVICE
WHERE BL.BLACKLIST_DEVICE IS NULL


INSERT INTO BESUCH (DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL)
	SELECT DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL
	FROM BESUCH
	WHERE NOT EXISTS (
		SELECT BLACKLIST_DEVICE
		FROM BLACKLIST
		WHERE BLACKLIST.BLACKLIST_DEVICE = BESUCH.DEVICE_ID
	)
	AND (SELECT COUNT(*)
			FROM BESUCH
			WHERE 1 = 1
			AND DEVICE_ID = '#{device_id}'
			ORDER BY end_time ASC
	) < 1


INSERT INTO BESUCH
(DEVICE_ID, MAC_PREFIX, LOC_NAME, VISIT_DATE, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL)
VALUES
('#{device_id}', '#{mac_prefix}', '#{location_name}', '#{visit_date}', '#{start_time}', '#{end_time}', '#{count}', '#{min_signal}', '#{max_signal}')
ON DUPLICATE KEY UPDATE
END_TIME = GREATEST(END_TIME, VALUES(END_TIME)),
START_TIME = LEAST(START_TIME, VALUES(START_TIME)),
MAX_SIGNAL = GREATEST(MAX_SIGNAL, VALUES(MAX_SIGNAL)),
MIN_SIGNAL = LEAST(MIN_SIGNAL, VALUES(MIN_SIGNAL)),
COUNT = COUNT+1


CREATE TABLE IF NOT EXISTS `BESUCH` (
`BESUCH_ID` bigint(20) NOT NULL AUTO_INCREMENT,
`DEVICE_ID` varchar(128) DEFAULT NULL,
`MAC_PREFIX` varchar(8) NOT NULL,
`LOC_NAME` varchar(255) DEFAULT NULL,
`VISIT_DATE` date DEFAULT NULL,
`START_TIME` time DEFAULT NULL,
`END_TIME` time DEFAULT NULL,
`COUNT` INT DEFAULT NULL,
`MIN_SIGNAL` SMALLINT DEFAULT NULL,
`MAX_SIGNAL` SMALLINT DEFAULT NULL,
PRIMARY KEY (`BESUCH_ID`),
UNIQUE KEY `BESUCH_ID` (`BESUCH_ID`),
KEY DEVICE (`DEVICE_ID`, `LOC_NAME`, `VISIT_DATE`, `START_TIME`)
) ENGINE=innodb;


CREATE TABLE IF NOT EXISTS `BLACKLIST` (
`BLACKLIST_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
`BLACKLIST_DEVICE` VARCHAR(128) DEFAULT NULL,
PRIMARY KEY(`BLACKLIST_ID`)
) ENGINE=innodb;


ALTER TABLE BLACKLIST 
ADD INDEX (BLACKLIST_DEVICE) 
USING BTREE
