INSERT INTO BESUCH (DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL)
 VALUES ('#{device_id}', '#{mac_prefix}', '#{location_name}', '#{start_time}', '#{end_time}', '#{count}', '#{min_signal}', '#{max_signal}')

SELECT COUNT(*) 
FROM BESUCH 
WHERE 1 = 1
AND DEVICE_ID = '#{device_id}'
ORDER BY END_TIME ASC

UPDATE BESUCH
SET END_TIME = '#{end_time}'
WHERE DEVICE_ID = '#{device_id}'


SELECT * 
FROM BESUCH
WHERE NOT EXISTS (
	SELECT 1
	FROM BLACKLIST
	WHERE BLACKLIST.BLACKLIST_DEVICE = BESUCH.DEVICE_ID
)

SELECT *
FROM BESUCH AS BE
LEFT JOIN BLACKLIST AS BL ON BE.DEVICE_ID = BL.BLACKLIST_DEVICE
WHERE BL.BLACKLIST_DEVICE IS NULL


INSERT INTO BESUCH (DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL)
	SELECT DEVICE_ID, MAC_PREFIX, LOC_NAME, START_TIME, END_TIME, COUNT, MIN_SIGNAL, MAX_SIGNAL
	FROM BESUCH
	WHERE NOT EXISTS (
		SELECT BLACKLIST_DEVICE
		FROM BLACKLIST
		WHERE BLACKLIST.BLACKLIST_DEVICE = BESUCH.DEVICE_ID
	)
	AND (SELECT COUNT(*)
			FROM BESUCH
			WHERE 1 = 1
			AND DEVICE_ID = '#{device_id}'
			ORDER BY end_time ASC
	) < 1

