require './Connect.rb'

#Creates all of the tables needed for the visits
#Should be run only once
	
@db.query("CREATE TABLE `VISITS`(
`VISIT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
`DEVICE_MAC` varchar(128) DEFAULT NULL,
`LOCATION_ID` varchar(128) DEFAULT NULL,
`VISIT_TIME` datetime DEFAULT NULL,
`VISIT_DB` varchar(128) DEFAULT NULL,
PRIMARY KEY(VISIT_ID))")

@db.query("CREATE TABLE `BLACKLIST` (
  `BLACKLIST_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `BLACKLIST_DEVICE` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY(`BLACKLIST_ID`)
  ) ENGINE=innodb;")

@db.query("CREATE TABLE `BESUCH` (
`BESUCH_ID` bigint NOT NULL AUTO_INCREMENT,
`DEVICE_ID` varchar(128) DEFAULT NULL,
`MAC_PREFIX` varchar(8) NOT NULL,
`LOC_NAME` varchar(255) DEFAULT NULL,
`VISIT_DATE` date DEFAULT NULL,
`START_TIME` time DEFAULT NULL,
`END_TIME` time DEFAULT NULL,
`COUNT` INT DEFAULT NULL,
`MIN_SIGNAL` SMALLINT DEFAULT NULL,
`MAX_SIGNAL` SMALLINT DEFAULT NULL,
PRIMARY KEY (`BESUCH_ID`),
UNIQUE KEY `BESUCH_ID` (`BESUCH_ID`),
KEY DEVICE (`DEVICE_ID`, `LOC_NAME`, `VISIT_DATE`, `START_TIME`)
) ENGINE=innodb;")

rs = @db.query("SHOW TABLES")

rs.each do |x|
	puts x
end